Personel.UI/Models/EntityFramework/Departman.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel.UI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departman()
        {
            this.Personel = new HashSet<Personel>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personel> Personel { get; set; }
    }
}

Personel.UI/Controllers/DepartmanController.cs
using Personel.UI.Models.EntityFramework;
using Personel.UI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Personel.UI.Controllers
{
    [Authorize(Roles = "A,U")]
    public class DepartmanController : Controller
    {
        PersonelDBEntities db = new PersonelDBEntities();
        
        
        public ActionResult Index()
        {
            var model = db.Departman.ToList();
            //int a = 0, b = 10;
            //int c = b / a; // runtime error oluşturmak için
            return View(model);
        }

        [HttpGet]
        public ActionResult Yeni()
        {

            return View("DepartmanForm", new Departman());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Departman departman)
        {
            if (!ModelState.IsValid)
            {
                return View("DepartmanForm");
            }

            MesajViewModel model = new MesajViewModel();
            if (departman.Id==0)
            {
                db.Departman.Add(departman);
                model.Mesaj =departman.Ad+ " departmanı eklendi";
            }
            else
            {
                var guncellenecekDepartman = db.Departman.Find(departman.Id);
                if (guncellenecekDepartman==null)
                {
                    return HttpNotFound();
                }
                guncellenecekDepartman.Ad = departman.Ad;
                model.Mesaj = departman.Ad + " departmanı güncellendi";
            }
            db.SaveChanges();
            model.Status = true;
            model.LinkText = "Departman Listesi";
            model.Url = "/Departman";
            return View("_Mesaj",model);
        }

        public ActionResult Guncelle(int id)
        {
            var model = db.Departman.Find(id);
            if (model!=null)
            {
                return View("DepartmanForm", model);
            }
            return HttpNotFound(); 
        }

        public ActionResult Sil(int id)
        {
            var silinecekDepartman = db.Departman.Find(id);
            if (silinecekDepartman==null)
            {
                return HttpNotFound();
            }
            db.Departman.Remove(silinecekDepartman);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Personel.UI/Controllers/PersonelController.cs
using Personel.UI.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Personel.UI.ViewModels;

namespace Personel.UI.Controllers
{
    [Authorize(Roles = "A,U")]
    public class PersonelController : Controller
    {
        PersonelDBEntities db = new PersonelDBEntities();
        
        [OutputCache(Duration =30)] // aşağıdaki db sorgusunu cache e atıp 30saniyede bir yenilemesini sağlıyor büyü ksorgularda performans arttırıcı olarak kullanılabilir fakat yeni eklenen personel ya da güncellenen personel varsa 30sn dolduktan sonra listede görüntülenebilir
        public ActionResult Index()
        {
            var model = db.Personel.Include(x=>x.Departman).ToList();
            return View(model);
        }
        
        public ActionResult Yeni()
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = new Personel.UI.Models.EntityFramework.Personel()
            };
            return View("PersonelForm",model
                );
        }

        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Personel.UI.Models.EntityFramework.Personel personel)
        {
            if (!ModelState.IsValid)
            {
                var model = new PersonelFormViewModel()
                {
                    Departmanlar = db.Departman.ToList(),
                    Personel = personel
                };
                return View("PersonelForm", model);
            }
            if (personel.Id==0) // Kaydetme
            {
                db.Personel.Add(personel);
            }
            else //Güncelleme
            {
                db.Entry(personel).State = System.Data.Entity.EntityState.Modified;   
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Guncelle(int id)
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar=db.Departman.ToList(),
                Personel=db.Personel.Find(id)
            };
            return View("PersonelForm",model);
        }

        public ActionResult Sil(int id)
        {
            var silinecekPersonel = db.Personel.Find(id);
            if (silinecekPersonel==null)
            {
                return HttpNotFound();
            }
            db.Personel.Remove(silinecekPersonel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelleriListele(int id)
        {
            var model = db.Personel.Where(x=>x.Departman.Id==id).ToList();
            return PartialView(model);
        }

        public ActionResult ToplamMaas()
        {
            ViewBag.Maas = db.Personel.Sum(x=>x.Maas);
            return PartialView();
        }
    }
}

Personel.UI/Views/Departman/DepartmanForm.cshtml
@model Personel.UI.Models.EntityFramework.Departman
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mesaj">

</div>
@using (Ajax.BeginForm("Kaydet", "Departman", new AjaxOptions {HttpMethod="POST",UpdateTargetId="mesaj" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(x => x.Ad)
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Ad)
    </div>
    @Html.HiddenFor(x => x.Id)
    <button type="submit" class="btn btn-success">Kaydet</button>
}

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Personel.UI/Views/Departman/Index.cshtml
@using Personel.UI.Models.EntityFramework
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a class="btn btn-success" href="/Departman/Yeni">Yeni Departman</a>
<h2>Departman Listesi</h2>
<table class="table table-bordered" id="tblDepartmanlar">
    <thead>
        <tr>
            <th>Id</th>
            <th>Ad</th>
            <th>Guncelle</th>
            <th>Sil</th>
            <th>Personeller</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var departman in Model)
        {
            <tr>
                <td>@departman.Id</td>
                <td>@departman.Ad</td>
                <td><a class="btn btn-primary" href="/Departman/Guncelle/@departman.Id">Guncelle</a></td>
                <td><a class="btn btn-warning btnDepartmanSil" data-id="@departman.Id">Sil</a></td>
                @*<td>@Html.ActionLink("Personelleri Göster","PersonelleriListele","Personel",new {id=departman.Id},new {@class="btn btn-primary" })</td>*@
                <td>@Ajax.ActionLink("Personelleri Göster", "PersonelleriListele", "Personel", new { id = departman.Id }, new AjaxOptions { HttpMethod = "GET",UpdateTargetId="personelListesi" }, new { @class = "btn btn-primary" })</td>
            </tr>
        }
    </tbody>
</table>


<div id="personelListesi"></div>

Personel.UI/Views/Departman/Yeni.cshtml
@model Personel.UI.Models.EntityFramework.Departman
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Yeni", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.Ad)
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-success">Ekle</button>
}