Personel.UI/Controllers/SecurityController.cs
using Personel.UI.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Personel.UI.Controllers
{
   
    public class SecurityController : Controller
    {
        PersonelDBEntities db = new PersonelDBEntities();

        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]    
        [HttpPost]
        public ActionResult Login(Kullanici kullanici)
        {
            var kullaniciKontrol = db.Kullanici.FirstOrDefault(x=>x.Ad==kullanici.Ad && x.Sifre==kullanici.Sifre);
            if (kullaniciKontrol!=null)
            {
                FormsAuthentication.SetAuthCookie(kullaniciKontrol.Ad, false);
                return RedirectToAction("Index","Departman");
            }
            else
            {
                ViewBag.Mesaj = "GEçersiz kullanıcı adı ya da şifre";
                return View();
            }
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

Personel.UI/Views/Security/Login.cshtml
@model Personel.UI.Models.EntityFramework.Kullanici 
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>

<body>
   
    <div class="container">
        <h2>Lütfen Giriş Yapınız</h2>
        @ViewBag.Mesaj
        @using (Html.BeginForm("Login", "Security", FormMethod.Post))
        {
            <div class="form-group">
                @Html.LabelFor(x => x.Ad)
                @Html.TextBoxFor(x => x.Ad, new { @class = "form-control", placeholder = "Kullanıcı Adı" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Sifre)
                @Html.PasswordFor(x => x.Sifre, new { @class = "form-control", placeholder = "Parola" })
            </div>
            <button type="submit" class="btn btn-block btn-success">Giriş Yap</button>
        }
    </div>
</body>
</html>